language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

      
branches:
  only:
    - master
    
rust:
  - stable
  - beta
  - nightly
  
notifications:
  email:
    - scott.rangeley@hotmail.com
    
script: 
     - cargo test
     
before_script:
  - rustc --version
  - cargo --version
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
      
after_success=
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify

