language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
  email:
    - scott.rangeley@hotmail.com
script: 
     - cargo test
before_script:
  - rustc --version
  - cargo --version
branches:
  only:
    - master